data_source localkube:
  type: postgres
  connection:
    host: soda-database
    port: 5432
    username: ${{ secrets.POSTGRES_USERNAME }}
    password: ${{ secrets.POSTGRES_PASSWORD }}
    database: postgres
  schema: public

soda_cloud:
  host: cloud.soda.io
  api_key_id: ${{ secret.API_KEY_ID }}
  api_key_secret: ${{ secret.API_KEY_SECRET }}
  
